language: php

cache:
  directories:
  - "$HOME/.composer/cache"

matrix:
  include:
  - php: '7.0'
  - php: '7.1'
  - php: '7.2'
    env: COVERAGE=yes
  - php: '7.3'
  allow_failures:
  - php: '7.2'
    env: COVERAGE=yes

before_install:
- echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
- |
  if [[ $COVERAGE != yes ]]; then
    phpenv config-rm xdebug.ini || echo "xdebug not available";
  fi;

install:
- composer install --prefer-dist --no-progress --no-suggest --ansi

script:
- |
  if [[ $COVERAGE = yes  ]]; then
    composer coverage;
  else
    composer test;
  fi;

after_success:
- |
  if [[ $COVERAGE = yes ]]; then
      bash <(curl -s https://codecov.io/bash) -s build/coverage/clover -f "*.xml";
      wget https://scrutinizer-ci.com/ocular.phar;
      php ocular.phar code-coverage:upload --format=php-clover build/coverage/clover.xml;
  fi;