services:
    Symfony\Component\Console\Input\InputInterface:
        alias: monorepo.input
    Symfony\Component\Console\Output\OutputInterface:
        alias: monorepo.output
    Psr\Log\LoggerInterface:
        alias: monorepo.logger

    monorepo.input:
        class: Symfony\Component\Console\Input\ArgvInput
    monorepo.output:
        class: Symfony\Component\Console\Output\ConsoleOutput
    monorepo.app:
        class: Monorepo\Console\Application
    monorepo.logger:
        class: Monorepo\Console\Logger
    monorepo.dispatcher:
        class: Monorepo\Event\EventDispatcher
    monorepo.config:
        class: Monorepo\Config\Config
        calls:
            - ['setCacheDir',['%monorepo.cache_dir%']]
            - ['setRootDir',['%monorepo.root_dir%']]
            - ['setContainerId',['%monorepo.container_id%']]
    monorepo.runner:
        class: Monorepo\Processor\Runner
    monorepo.filesystem:
        class: Monorepo\Processor\Filesystem

    # event subscribers
    Monorepo\Processor\:
        resource: '../src/Processor/*'
        #exclude: '../src/Command/{AbstractCommand,CommandInterface}'

    # command lists
    Monorepo\Command\:
        resource: '../src/Command/*'
        exclude: '../src/Command/{AbstractCommand,CommandInterface}'
