services:
    Symfony\Component\Console\Input\InputInterface:
        alias: monorepo.input
    Symfony\Component\Console\Output\OutputInterface:
        alias: monorepo.output
    Psr\Log\LoggerInterface:
        alias: monorepo.logger

    monorepo.input:
        class: Symfony\Component\Console\Input\ArgvInput
    monorepo.output:
        class: Symfony\Component\Console\Output\ConsoleOutput
    monorepo.app:
        class: Monorepo\Console\Application
    monorepo.logger:
        class: Monorepo\Console\Logger
    monorepo.dispatcher:
        class: Monorepo\Event\EventDispatcher

    Monorepo\Processor\SplitProcessor: ~
    Monorepo\Processor\Runner: ~
    Monorepo\Config\Config: ~
    # command lists
    Monorepo\Command\SplitCommand: ~